version: '3.8'
services:
  webserver:
    build:
      context: .
      dockerfile: ./packages/webserver/backend.Dockerfile
    environment:
      - FRONTEND_ORIGIN=http://localhost:3000
    ports:
      - "8080:8080"
    volumes:
      - ./packages/webserver/logs:/app/logs

  webui:
    build:
      context: .
      dockerfile: ./packages/webui/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - webserver 
